// you are given two String S and T
// String t is generated by random suffling String s , and then add on emore letter
// at a random positon. Return the letter that wasadded to it
 // for ex--> Input--> S = "abcd", t = "abcde"
 // output--> "e"
package String_Problems;

public class Find_The_Difference {
  public   static char findthediff(String s, String t){
        int total =0;
        for (int i =0;i<t.length();i++){
            total = total+ t.charAt(i);
        }
        for (int i=0;i<s.length();i++){
            total = total- s.charAt(i);
        }
        return (char) total;
    }
    public static void main(String[] args) {
        String s = "abcd";
        String t ="abcde";
        System.out.println(findthediff(s,t));
    }
}
